### ISSUE TITLE
Thousands separation for Servers/Members count

### ISSUE THREAD

**Issue by fbrettnich** [Penol/issuetracker#1]
Please add a thousands separator to the Servers/Members count in the status of the Discord Bot.
It just looks nicer and makes the number easier to read 😄 

120310 => 120.310 / 120 310

![Bot Status](https://cdn.f3lix.net/d/ddiq1P)

@AFink you already wanted to do that 😆

**Comment by AFink** [comment]
Thank you for your annotation, I will implement it in the next update.

**Comment by fbrettnich** [comment]
Inactive
